export const FETCH_EMAILS_START = 'FETCH_EMAILS_START';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_FAIL = 'FETCH_EMAILS_FAIL';
export const EMAILS_PAGE_CHANGE = 'EMAILS_PAGE_CHANGE';