export const FETCH_EMAILS_START = 'FETCH_EMAILS_START';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_FAIL = 'FETCH_EMAILS_FAIL';
export const EMAILS_PAGE_CHANGE = 'EMAILS_PAGE_CHANGE';


export const ITEMS_INIT = 'ITEMS_INIT';
export const SELECT_ITEM = 'ITEMS_INIT';
export const FETCH_ITEMS_START = 'FETCH_ITEMS_START';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const ITEMS_PAGE_CHANGE = 'ITEMS_PAGE_CHANGE';
export const ITEMS_UPDATE_FILTER = 'ITEMS_UPDATE_FILTER';

